renting/urls.py
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from renting.authentication import logout_view, login_view

from management import urls as management_urls
from website import urls as student_urls

from adminplus.sites import AdminSitePlus

admin.site = AdminSitePlus()
admin.autodiscover()

# Segment.io
import analytics
analytics.write_key = 'WvODpdaIThxlqclZyp9Ri6BxvacynhDm'


urlpatterns = [

    #Authentication
    # url(r'^login/$', login_view, name='login'),
    # url(r'^logout/$', logout_view, name='logout'),

    # Website apps
    url(r'^management/', include(management_urls, namespace='management')),
    url(r'^', include(student_urls)),


    # Django Admin URLS
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'media'}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns(
    '', url(r'^dbmail/', include('dbmail.urls')),
)

website/urls.py
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.conf.urls import url
from website.views import MainStudentDashboardView, ProfileView, InviteUpdateView, StaticView, \
    QuizProfileInformation, QuizUpdateSlideView, RoomMateMatchView, CodeIndex, UserConversationView, \
    PeerProfileAjaxView, SearchPeersAjaxView, GoogleVerification, UploadUserProfileImageView, UserMessagesAjax, \
    update_bio, SelectUnitView, SelectBedView

urlpatterns = [
    url(r'^getting-started/(?P<invite_code>[^/]+)$', MainStudentDashboardView.as_view(), name='getting-started'),
    url(r'^profile/$', ProfileView.as_view(), name='user_profile'),
    url(r'^profile_v2/$', MainStudentDashboardView.as_view(), name='user_profile_v2'),
    url(r'^invite_update/$', InviteUpdateView.as_view(), name='invite_update'),
    url(r'^quiz-profile/$', QuizProfileInformation.as_view(), name='quiz_profile'),
    url(r'^quiz-slide/$', QuizUpdateSlideView.as_view(), name='quiz_slide'),
    url(r'^room-mate-matching/$', RoomMateMatchView.as_view(), name='roommate_selection'),
    url(r'^user-conversation/(?P<conversation_uuid>.*)/$', UserConversationView.as_view(), name='user-conversation'),
    url(r'^user-profile-ajax/(?P<peer_id>.*)/$', PeerProfileAjaxView.as_view(), name='user-profile-ajax'),
    url(r'^search-peers-ajax/$', SearchPeersAjaxView.as_view(), name='search-peers-ajax'),
    url(r'^upload-image-ajax/$', UploadUserProfileImageView.as_view(), name='upload-image-ajax'),
    url(r'^user-messages-ajax/$', UserMessagesAjax.as_view(), name='user-messages-ajax'),
    url(r'^google0f68347ff74b158a.html$', GoogleVerification.as_view(), name='google0f68347ff74b158a.html'),
    url(r'update-bio/$', update_bio, name='update-bio'),
    url(r'^select_unit/$', SelectUnitView.as_view(), name='select_unit'),
    url(r'^select_bed/$', SelectBedView.as_view(), name='select_bed'),
    url(r'^$', CodeIndex.as_view(), name='code_index'),
    url(r'^(?P<page>.+\.html)$', StaticView.as_view(), name='static'),
    url(r'^(?P<page>.+\.txt)$', StaticView.as_view(), name='static'),
    url(r'^(?P<page>)$', StaticView.as_view(), name='static'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models.py
import os
import uuid
import random
import cPickle as pickle
from datetime import datetime
import requests
from requests.exceptions import ConnectionError
import time
from itertools import chain
from django.utils.lru_cache import lru_cache
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.conf import settings
# from django.contrib.auth.models import User
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.db import models
from django.db.models import Model, Q, Prefetch, F, Sum, Case, When, Count

from management.models import Invitation, OrganizationSocialHabitQuestion, OrganizationSocialHabitAnswer, Property, \
    AssignmentPeriod, Unit, UnitType, Stage, PendingAssignment


def content_file_name(instance, filename):
    return '/'.join(['content', instance.user.username, filename])


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(email,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    GENDER_UNKNOWN = 'U'
    GENDER_MALE = 'M'
    GENDER_FEMALE = 'F'

    GENDER_CHOICES = (
        (GENDER_UNKNOWN, 'Unknown'),
        (GENDER_MALE, 'Male'),
        (GENDER_FEMALE, 'Female')
    )

    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    first_name = models.CharField('first name', max_length=30, blank=True)
    last_name = models.CharField('last name', max_length=30, blank=True)
    gender = models.CharField('gender', max_length=1, choices=GENDER_CHOICES, default=GENDER_UNKNOWN)
    available_properties = models.ManyToManyField(Property, related_name='assigned_users',
                                                  help_text="Only selected properties can send invites for this user.")
    allow_co_educational_groups = models.BooleanField(default=False, verbose_name='Enable coed matching. Coed limits your matching to other coed users. ')
    hidden = models.BooleanField(default=False, verbose_name='Hide your profile from matching request')
    disable_emails = models.BooleanField(default=False, verbose_name='Turn off email notifications')
    points = models.PositiveSmallIntegerField(default=50)
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def clean(self):
        self.email = self.email.lower()
        super(User, self).clean()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.email = self.email.lower()
        super(User, self).save(force_insert, force_update, using, update_fields)

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __unicode__(self):              # __str__ on Python 3
        return self.email

    def feed_str(self):
        return self.full_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    @property
    def is_superuser(self):
        return self.is_admin

    @property
    def full_name(self):
        return u"{} {}".format(self.first_name.capitalize(), self.last_name.capitalize())

    @property
    def stage(self):
        return Stage.objects.filter(min_points__lte=self.points, max_points__gte=self.points).first()


class UserProfile(Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile')

    # Traitify Results
    personality_types = models.TextField(null=True)
    personality_traits = models.TextField(null=True)

    # Bio
    bio = models.TextField(null=True, blank=True)

    # Social Links
    twitter_url = models.URLField(null=True, max_length=250, blank=True)
    facebook_url = models.URLField(null=True, max_length=250, blank=True)
    pinterest_url = models.URLField(null=True, max_length=250, blank=True)
    linkedin_url = models.URLField(null=True, max_length=250, blank=True)
    instagram_url = models.URLField(null=True, max_length=250, blank=True)
    snapchat_url = models.URLField(null=True, max_length=250, blank=True)
    google_plus_url = models.URLField(null=True, max_length=250, blank=True)

    # Profile Image
    profile_image = models.ImageField(blank=True, null=True, upload_to='uploads/avatar/%Y/%m/%d/')
    profile_image_bg = models.ImageField(blank=True, null=True, upload_to='uploads/avatar_bg/%Y/%m/%d/')
    image_url = models.CharField(blank=True, null=True, max_length=250)
    bg_url = models.CharField(blank=True, null=True, max_length=250)

    def __unicode__(self):
        return self.user.email

    @lru_cache(maxsize=2048)
    def get_personality_traits_json(self):
        return pickle.loads(str(self.personality_traits)) if self.personality_traits else {}

    @lru_cache(maxsize=2048)
    def get_personality_types_json(self):
        return pickle.loads(str(self.personality_types)) if self.personality_types else {}

    def _get_image_url(self, results):
        photo = {}
        for photo in results.get('photos', []):
            if photo.get('isPrimary'):
                return photo.get('url')

        return photo.get('url')

    def _get_random_background_image(self):
        photos = filter(lambda photo_file: '@' not in photo_file, os.listdir(settings.BG_ROOT))
        return os.path.join(settings.BG_URL, random.choice(photos))

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        try:
            results = requests.get(
                settings.FULLCONTACT_API_URL.format(self.user.email, settings.FULLCONTACT_API_KEY)).json()
        except ConnectionError:
            time.sleep(1)
            results = requests.get(
                settings.FULLCONTACT_API_URL.format(self.user.email, settings.FULLCONTACT_API_KEY)).json()
        for social_profile in results.get("socialProfiles", []):
            validate = URLValidator()
            if social_profile.get("type") == 'facebook':
                self.facebook_url = social_profile.get('url')
                try:
                    validate(self.facebook_url)
                except ValidationError, e:
                    self.facebook_url = None
            elif social_profile.get("type") == 'twitter':
                self.twitter_url = social_profile.get('url')
                try:
                    validate(self.twitter_url)
                except ValidationError, e:
                    self.twitter_url = None
            elif social_profile.get("type") == 'pinterest':
                self.pinterest_url = social_profile.get('url')
                try:
                    validate(self.pinterest_url)
                except ValidationError, e:
                    self.pinterest_url = None
            elif social_profile.get("type") == 'linkedin':
                self.linkedin_url = social_profile.get('url')
                try:
                    validate(self.linkedin_url)
                except ValidationError, e:
                    self.linkedin_url = None

            if self.bio is None and social_profile.get('bio'):
                self.bio = social_profile.get('bio')

        if self.image_url is None:
            self.image_url = self._get_image_url(results)

        if self.bg_url is None:
            self.bg_url = self._get_random_background_image()

        super(UserProfile, self).save(force_insert=False, force_update=False, using=None, update_fields=None)


class QuizResult(Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    traitify_assessment_id = models.CharField(null=True, max_length=50)

class RelationshipBaseManager(models.Manager):
    pass

class RelationshipNotDeletedManager(RelationshipBaseManager):
    def get_queryset(self):
        return super(RelationshipNotDeletedManager, self).get_queryset().filter(is_deleted=False)

class RelationshipAllEntriesManager(RelationshipBaseManager):
    pass

class Relationship(Model):
    NOT_ROOMMATE = 'N'
    DIRECT_ROOMMATE = 'D'
    PROPOSED_BY_END_USER = 'E'
    PROPOSED_BY_START_USER = 'S'
    ROOMMATE_CHOICES = (
        (NOT_ROOMMATE, 'Not roommates'),
        (DIRECT_ROOMMATE, 'Direct roommates'),
        (PROPOSED_BY_END_USER, 'Proposed by end_user'),
        (PROPOSED_BY_START_USER, 'Proposed by start_user'),
    )

    group = models.ForeignKey('Group', null=True, blank=True, related_name='relations')
    start_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='start_user')
    # organization_invitation = models.ForeignKey(OrganizationInvitation, blank=True, null=True)
    invitation = models.ForeignKey(Invitation)
    end_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='end_user')
    end_user_approved = models.BooleanField(default=False)
    invite_datetime = models.DateTimeField(default=datetime.now)
    approval_datetime = models.DateTimeField(null=True)
    # This field used for relations via friends, for direct relation this value is None
    via_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, default=None)
    # This field used for restricting deleting of relations

website/templates/includes/personality/detail.html
<div class="block">
    <div class="block-header border-b bg-primary-dark text-white">
        <h3 class="block-title">
            {% if personality_detail.title == 'Complement' %}
                <i class="fa fa-thumbs-o-up"></i> What brightens your day
            {% elif personality_detail.title == 'Conflict' %}
                <i class="fa fa-thumbs-o-down"></i>  What clouds your day
            {% else %}
                {{ personality_detail.title }}
            {% endif %}
        </h3>
    </div>
    <div class="block-content block-content-full text-center">
        <div class="text-left">{{ personality_detail.body }}</div>
    </div>
</div>

website/templates/includes/personality/user_card.html
{% load social_share %}


<div class="block">
  <div id="userprofile_bg" data-toggle="tooltip" data-placement="top" title="Click to upload background image"
      {% if user.profile.profile_image_bg %}
       class="block-content block-content-full text-center bg-image"
       style="background-image: url('{{ user.profile.profile_image_bg.url }}');"
      {% elif user.profile.bg_url %}
       class="block-content block-content-full text-center bg-image"
       style="background-image: url('{{ user.profile.bg_url }}');"
      {% else %}
       class="block-content block-content-full text-center bg-primary-dark"
      {% endif %}>
    <img id="userprofile_image" data-toggle="tooltip" data-placement="left" title="Click to upload profile image"
         class="img-avatar img-avatar96 img-avatar-thumb"
         src="
             {% if user.profile.profile_image %}{{ user.profile.profile_image.url }}{% else %}/static/img/avatars/avatar4.jpg{% endif %}"
         alt="">
  </div>
  <div class="block-content block-content-full text-center">
    <div class="font-w600 push-5">{{ user.first_name }} {{ user.last_name }}</div>
    <div>
      Share via
      {% with user.id|stringformat:"s" as user_id %}
        {% with "http://xxx.com/profile_v2/?user-profile="|add:user_id as url %}
          {% post_to_facebook url "Post to Facebook!" %}
          {% post_to_twitter "I'm looking for roommates! Login at {{ property.name }} and search for me using code: {{ user.id }}. Thanks! " url "Post to Twitter" %}
          {% post_to_gplus url "Post to Google+!" %}
        {% endwith %}
      {% endwith %}
    </div>
    <div class="profile-details-block">
      <div class="font-w600 push-5">Contract Details</div>

      <p class="profile-details">Unit Type: {{ invite.unit_type.name }}</p>
      {% if can_select_unit and is_user_stage and is_leader %}
        <a data-toggle="modal" data-target="#select-unit-bed-modal">
          <p class="profile-details">Unit:
            {% if assignment and assignment.unit %}
              <span class="user-unit">{{ assignment.unit.name }}</span>
              {% if assignment.room %}
                <p class="profile-details">Room: <span class="user-room">{{ assignment.room.name }}</span></p>
              {% endif %}
              {% if assignment.bed %}
                <p class="profile-details">Bed: <span class="user-bed">{{ assignment.bed.name }}</span></p>
              {% endif %}
            {% else %}
              Select unit and bed
            {% endif %}
          </p>
        </a>
      {% else %}
        {% if assignment and assignment.unit %}
          <p class="profile-details">
            Unit: <span class="user-unit">{{ assignment.unit.name }} </span>
            {% if assignment.room %}
              Room: <span class="user-room">{{ assignment.room.name }} </span>
              {% if assignment.bed %}
                Bed: <span class="user-bed">{{ assignment.bed.name }}</span>
              {% endif %}
            {% endif %}
          </p>
        {% endif %}
      {% endif %}

      {% if invite.contract_type %}
        <p class="profile-details">Contract Type: {{ invite.contract_type.name }}</p>
      {% endif %}
      {% if user.gender != 'U' %}
        <p class="profile-details">Gender: {{ user.get_gender_display }}</p>
      {% endif %}
      <p class="profile-details">Your Permissions: {{ user.stage.label }}</p>
      <p class="profile-details">Current Property Stage: {{ current_stage }}</p>
      {% if property.file %}
        <p class="profile-details"><a href="{{ property.file.url }}" target="_blank">Resources</a></p>
      {% endif %}
    </div>
    <div class="text-muted">{{ user.profile.get_personality_types_json.personality_blend.name }}</div>
    <div class="text-left">{{ user.profile.get_personality_types_json.personality_blend.description }}</div>
    <div class="block-content">
      <div class="row items-push text-center">
        {% for attribute in user.profile.get_personality_types_json.personality_types|slice:"6" %}
          <div class="col-xs-6 {% if not forloop.counter|divisibleby:"2" %}border-r{% endif %}"
               data-placement="left"
               data-content="{{ attribute.personality_type.description }}"
               data-toggle="popover"
               title="{{ attribute.personality_type.name }}">
            <div class="push-5">{{ attribute.personality_type.name }}</div>
            <div class="h5 font-w300 text-muted">{{ attribute.score | floatformat:"2" }}%</div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<div class="block">
  <div class="block-header border-b bg-primary-dark text-white">
    <ul class="block-options">
      <li>
        <a data-toggle="modal" data-target="#bio-modal" class="text-white" style="cursor: pointer;">edit</a>
      </li>
    </ul>
    <h3 class="block-title">About Me</h3>
  </div>

  <div class="block-content block-content-full text-center">
    <div id="user_bio" class="text-left">
      {% if user.profile.bio %}{{ user.profile.bio }}{% else %}No bio set{% endif %}</div>
  </div>
</div>

<div class="block">
  <div class="block-header border-b bg-primary-dark text-white">
    <h3 class="block-title">Personality</h3>
  </div>
  {% if user.profile.personality %}
    <div class="block-content block-content-full text-center">
      <div class="block-content">
        <div class="row items-push text-center">
          {% for item1, item2 in user.profile.personality %}
            <div class="col-xs-12">
              <table class="custom-table">
                <colgroup>
                  <col>
                  <col>
                </colgroup>
                <thead>
                <tr>
                  <th class="text-center font-w400 border-r">
                    <div class="push-5">{{ item1.0 }}</div>
                  </th>
                  <th class="text-center font-w400">
                    <div class="push-5">{{ item2.0 }}</div>
                  </th>
                </tr>
                </thead>
                <thead>
                <tr>
                  <td class="h5 font-w300 text-muted border-r">{{ item1.1 }}</td>
                  <td class="h5 font-w300 text-muted">{{ item2.1 }}</td>
                </tr>
                </thead>
              </table>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  {% else %}
    <div class="block-content block-content-full text-center">
      <div class="text-left">No personality attributes set</div>
    </div>
  {% endif %}
</div>

<div style="display: none;" class="modal" id="bio-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="block block-themed block-transparent remove-margin-b">
        <div class="block-header bg-primary-dark">
          <ul class="block-options">
            <li>
              <button data-dismiss="modal" type="button"><i class="si si-close"></i></button>
            </li>
          </ul>
          <h3 class="block-title">About Me</h3>
        </div>
        <div class="block-content">
          <form id="bio_form" method="post">
            {% csrf_token %}
            {{ form }}
          </form>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-sm btn-default" type="button" data-dismiss="modal">Close</button>
        <button id="bio_form_submit" class="btn btn-sm btn-primary" type="submit"><i class="fa fa-check"></i> Ok
        </button>
      </div>
    </div>
  </div>
</div>


<div id="select-unit-bed-modal" class="modal fade" tabindex="-1" aria-hidden="true" role="dialog">
  <div class="modal-large modal-dialog modal-dialog-popin">
    <div class="modal-content">
      <div class="block block-themed block-transparent">
        <div class="block-header bg-primary-light">
          <ul class="block-options">
            <li>
              <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"></button>
            </li>
            <li>
              <button data-dismiss="modal" type="button"><i class="si si-close"></i></button>
            </li>
          </ul>
          <h3 class="block-title">Please select a bed</h3>
        </div>
        <div class="block-content">
          <div class="row text-center">
            <div class="col-sm-6 col-sm-offset-3">
              Based on your group preferences we're showing units with room for you and
              <input id="select-group-size" type="number" name="group-size" placeholder="Group size"> others
            </div>
          </div>
          {% if form %}
            <form id="select-unit-bed-form" method="post">
              {% csrf_token %}

              <div class="block spinner-holder hide">
                <div class="block-content block-content-full text-center">
                  <i class="fa fa-spinner fa-spin fa-2x"></i>
                </div>
              </div>

              <div class="unit-bed-content">
                <div class="header-row row">
                  <div class="col-sm-4">
                    <h4 class="block-title">Unit</h4>
                  </div>
                  <div class="col-sm-8">
                    <h4 class="block-title">Unit <span id="unit-id"></span> Details</h4>
                  </div>
                </div>

                <div class="row">
                  <div class="col-sm-4">
                    <div class="block">
                      <select id="units-select" name="unit" class="form-control col-sm-4"></select>
                    </div>
                  </div>
                  <div class="col-sm-8">
                    <div class="center">
                      <a class="font-w600" href="javascript:void(0)">View Image</a>
                    </div>
                  </div>
                </div>
                <div class="header-row row">
                  <div class="block-title">Beds List</div>
                </div>
                <div id="beds-select" class="row"></div>
              </div>
            </form>
          {% endif %}
        </div>
      </div>
      <div class="modal-footer">
        {% if form %}
          <button id="select-unit-bed-submit" class="btn btn-info">Save</button>
        {% endif %}
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>