management/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from management.views import LoginView, logout_view, DashboardView, PropertyView, InvitationListView, \
    UserListView, UserUpdateView, UserCreateView, MatchesListView, \
    UnitTypeListView, UnitTypeCreateView, UnitTypeUpdateView, RoomTypeListView, RoomTypeCreateView, RoomTypeUpdateView,\
    OrganizationSocialHabitQuestionListView, OrganizationSocialHabitQuestionCreateView, \
    OrganizationSocialHabitQuestionUpdateView, UserDeleteView, SuggestedRoommateListView, ResidentImportListView, \
    MailTemplateListView, MailTemplateCreateView, MailTemplateUpdateView, MailTemplateDeleteView, PropertyFeedListView, \
    OrganizationSocialHabitQuestionDeleteView, GlobalSearchView, PlacementListView, \
    PlacementUsersView, StageView, RealtyImportListView, UnitCreateView, UnitUpdateView, DashboardChartsView, MainView, \
    PropertySettingsView,PropertySocialNetworkListView,PropertySocialNetworkCreateView,PropertySocialNetworkUpdateView, \
    PropertySocialNetworkDeleteView

urlpatterns = [
    # url(r'^getting-started/(?P<invite_code>[^/]+)$', MainStudentDashboardView.as_view(), name='getting-started'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^property/(?P<pk>[0-9]+)/$', PropertyView.as_view(), name='property'),
    url(r'^dashboard/(?P<property_id>\d+)/$', login_required(DashboardView.as_view()), name='dashboard'),
    url(r'^charts/(?P<property_id>\d+)/$', DashboardChartsView.as_view(), name='dashboard-charts'),
    url(r'^invitations/(?P<property_id>\d+)/$', InvitationListView.as_view(), name='invitation-list'),
    url(r'^user/(?P<property_id>\d+)/$', UserListView.as_view(), name='user-list'),
    url(r'^user/(?P<property_id>\d+)/(?P<pk>[0-9]+)/$', UserUpdateView.as_view(), name='user-update'),
    url(r'^user/(?P<property_id>\d+)/(?P<pk>[0-9]+)/delete$', UserDeleteView.as_view(), name='user-delete'),
    url(r'^user/(?P<property_id>\d+)/add/$', UserCreateView.as_view(), name='user-add'),
    url(r'^matches/(?P<property_id>\d+)/$', MatchesListView.as_view(), name='match-list'),
    url(r'^suggested_roommates/(?P<property_id>\d+)/$', SuggestedRoommateListView.as_view(),
        name='suggested-roommates-list'),
    url(r'^unit_type/(?P<property_id>\d+)/$', UnitTypeListView.as_view(), name='unit-type-list'),
    url(r'^unit_type/(?P<property_id>\d+)/(?P<pk>[0-9]+)/$', UnitTypeUpdateView.as_view(), name='unit-type-update'),
    url(r'^unit_type/(?P<property_id>\d+)/add/$', UnitTypeCreateView.as_view(), name='unit-type-add'),
    url(r'^room_type/(?P<property_id>\d+)/$', RoomTypeListView.as_view(), name='room-type-list'),
    url(r'^room_type/(?P<property_id>\d+)/(?P<pk>[0-9]+)/$', RoomTypeUpdateView.as_view(), name='room-type-update'),
    url(r'^room_type/(?P<property_id>\d+)/add/$', RoomTypeCreateView.as_view(), name='room-type-add'),
    url(r'^org_question/(?P<property_id>\d+)/$', OrganizationSocialHabitQuestionListView.as_view(),
        name='org-questions-list'),
    url(r'^org_question/(?P<property_id>\d+)/add/$', OrganizationSocialHabitQuestionCreateView.as_view(),
        name='org-question-add'),
    url(r'^org_question/(?P<property_id>\d+)/(?P<pk>[0-9]+)/$', OrganizationSocialHabitQuestionUpdateView.as_view(),
        name='org-question-update'),
    url(r'^org_question/(?P<property_id>\d+)/(?P<pk>[0-9]+)/delete$',
        OrganizationSocialHabitQuestionDeleteView.as_view(), name='org-question-delete'),
    url(r'^resident_import/(?P<property_id>\d+)/$', ResidentImportListView.as_view(), name='resident-import-list'),
    url(r'^realty_import/(?P<property_id>\d+)/$', RealtyImportListView.as_view(), name='realty-import-list'),
    url(r'^mail/(?P<property_id>\d+)/$', MailTemplateListView.as_view(), name='mail-template-list'),
    url(r'^mail/(?P<property_id>\d+)/(?P<pk>[0-9]+)/$', MailTemplateUpdateView.as_view(), name='mail-template-update'),
    url(r'^mail/(?P<property_id>\d+)/add$', MailTemplateCreateView.as_view(), name='mail-template-add'),
    url(r'^mail/(?P<property_id>\d+)/(?P<pk>[0-9]+)/delete/$', MailTemplateDeleteView.as_view(),
        name='mail-template-delete'),
    url(r'^placements/(?P<property_id>\d+)/units/create/$', UnitCreateView.as_view(), name='unit_create'),
    url(r'^placements/(?P<property_id>\d+)/units/(?P<pk>[0-9]+)/$', UnitUpdateView.as_view(), name='unit_update'),
    url(r'^placements/(?P<property_id>\d+)/(?P<period_id>\d+)/users/$', PlacementUsersView.as_view(), name='placement_create'),
    url(r'^placements/(?P<property_id>\d+)/$', PlacementListView.as_view(), name='placement_details'),
    url(r'^feed/(?P<property_id>\d+)/$', PropertyFeedListView.as_view(), name='feed'),
    url(r'^search_results/$', GlobalSearchView.as_view(), name='search'),
    url(r'^stages/(?P<property_id>\d+)/$', StageView.as_view(), name='stages'),
    url(r'^settings/(?P<property_id>\d+)/$', PropertySettingsView.as_view(), name='property_settings'),
    url(r'^social_networks/(?P<property_id>\d+)/$', PropertySocialNetworkListView.as_view(), name='social-networks-list'),
    url(r'^social_networks/(?P<property_id>\d+)/(?P<pk>[0-9]+)/$', PropertySocialNetworkUpdateView.as_view(), name='social-networks-update'),
    url(r'^social_networks/(?P<property_id>\d+)/add/$', PropertySocialNetworkCreateView.as_view(), name='social-networks-add'),
    url(r'^social_networks/(?P<property_id>\d+)/(?P<pk>[0-9]+)/delete/$', PropertySocialNetworkDeleteView.as_view(), name='social-networks-delete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

renting/urls.py
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from renting.authentication import logout_view, login_view

from management import urls as management_urls
from website import urls as student_urls

from adminplus.sites import AdminSitePlus

admin.site = AdminSitePlus()
admin.autodiscover()

# Segment.io
import analytics
analytics.write_key = 'WvODpdaIThxlqclZyp9Ri6BxvacynhDm'


urlpatterns = [

    #Authentication
    # url(r'^login/$', login_view, name='login'),
    # url(r'^logout/$', logout_view, name='logout'),

    # Website apps
    url(r'^management/', include(management_urls, namespace='management')),
    url(r'^', include(student_urls)),


    # Django Admin URLS
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'media'}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns(
    '', url(r'^dbmail/', include('dbmail.urls')),
)

website/urls.py
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.conf.urls import url
from website.views import MainStudentDashboardView, ProfileView, InviteUpdateView, StaticView, \
    QuizProfileInformation, QuizUpdateSlideView, RoomMateMatchView, CodeIndex, UserConversationView, \
    PeerProfileAjaxView, SearchPeersAjaxView, GoogleVerification, UploadUserProfileImageView, UserMessagesAjax, \
    update_bio, SelectUnitView, SelectBedView

urlpatterns = [
    url(r'^getting-started/(?P<invite_code>[^/]+)$', MainStudentDashboardView.as_view(), name='getting-started'),
    url(r'^profile/$', ProfileView.as_view(), name='user_profile'),
    url(r'^profile_v2/$', MainStudentDashboardView.as_view(), name='user_profile_v2'),
    url(r'^invite_update/$', InviteUpdateView.as_view(), name='invite_update'),
    url(r'^quiz-profile/$', QuizProfileInformation.as_view(), name='quiz_profile'),
    url(r'^quiz-slide/$', QuizUpdateSlideView.as_view(), name='quiz_slide'),
    url(r'^room-mate-matching/$', RoomMateMatchView.as_view(), name='roommate_selection'),
    url(r'^user-conversation/(?P<conversation_uuid>.*)/$', UserConversationView.as_view(), name='user-conversation'),
    url(r'^user-profile-ajax/(?P<peer_id>.*)/$', PeerProfileAjaxView.as_view(), name='user-profile-ajax'),
    url(r'^search-peers-ajax/$', SearchPeersAjaxView.as_view(), name='search-peers-ajax'),
    url(r'^upload-image-ajax/$', UploadUserProfileImageView.as_view(), name='upload-image-ajax'),
    url(r'^user-messages-ajax/$', UserMessagesAjax.as_view(), name='user-messages-ajax'),
    url(r'^google0f68347ff74b158a.html$', GoogleVerification.as_view(), name='google0f68347ff74b158a.html'),
    url(r'update-bio/$', update_bio, name='update-bio'),
    url(r'^select_unit/$', SelectUnitView.as_view(), name='select_unit'),
    url(r'^select_bed/$', SelectBedView.as_view(), name='select_bed'),
    url(r'^$', CodeIndex.as_view(), name='code_index'),
    url(r'^(?P<page>.+\.html)$', StaticView.as_view(), name='static'),
    url(r'^(?P<page>.+\.txt)$', StaticView.as_view(), name='static'),
    url(r'^(?P<page>)$', StaticView.as_view(), name='static'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/forms.py
from django import forms
from django.forms import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model
from django.db.models.fields import BLANK_CHOICE_DASH
from website.models import UserProfile
User = get_user_model()


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'gender', 'available_properties', 'allow_co_educational_groups')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'is_active', 'is_admin', 'first_name', 'last_name', 'gender',
                  'available_properties', 'allow_co_educational_groups')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class ManagerUserCreationForm(forms.ModelForm):
    is_manager = forms.BooleanField(initial=False, required=False, label='Manager')
    password1 = forms.CharField(label='Password', required=False,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Password confirmation', required=False,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'gender', 'password1', 'password2', 'is_manager')
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        self.property = kwargs.pop('property', None)
        super(ManagerUserCreationForm, self).__init__(*args, **kwargs)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def clean(self):
        if not self.cleaned_data['password1'] and self.cleaned_data['is_manager']:
            self.add_error('password1', 'You must provide password for managers')
        return super(ManagerUserCreationForm, self).clean()

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(ManagerUserCreationForm, self).save(commit=False)
        if self.cleaned_data['is_manager']:
            user.set_password(self.cleaned_data["password1"])
        else:
            user.set_unusable_password()
        if commit:
            user.save()
        if self.property:
            user.available_properties.add(self.property)
            if self.cleaned_data['is_manager']:
                self.property.managers.add(user)
        self.save_m2m()
        return user


class ManagerUserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'gender', 'points')
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'points': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class UserInformationForm(forms.ModelForm):
    gender = forms.ChoiceField(choices=BLANK_CHOICE_DASH + list(User.GENDER_CHOICES[1:]),
                               widget=forms.Select(attrs={'class': 'form-control required required-select first-tab-element'}))

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'gender', 'allow_co_educational_groups', 'hidden',
                  'disable_emails')
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control required first-tab-element'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control required first-tab-element'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control required first-tab-element'}),
            'allow_co_educational_groups': forms.CheckboxInput(attrs={'class': 'form-control first-tab-element'}),
            'hidden': forms.CheckboxInput(attrs={'class': 'form-control first-tab-element'}),
            'disable_emails': forms.CheckboxInput(attrs={'class': 'form-control first-tab-element'}),
        }


class UserProfileInformationForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('twitter_url', 'facebook_url', 'pinterest_url', 'linkedin_url', 'instagram_url',
                  'snapchat_url', 'google_plus_url')
        widgets = {
            'twitter_url': forms.TextInput(attrs={'class': 'form-control url-field first-tab-element'}),
            'facebook_url': forms.TextInput(attrs={'class': 'form-control url-field first-tab-element'}),
            'pinterest_url': forms.TextInput(attrs={'class': 'form-control url-field first-tab-element'}),
            'linkedin_url': forms.TextInput(attrs={'class': 'form-control url-field first-tab-element'}),
            'instagram_url': forms.TextInput(attrs={'class': 'form-control url-field first-tab-element'}),
            'snapchat_url': forms.TextInput(attrs={'class': 'form-control url-field first-tab-element'}),
            'google_plus_url': forms.TextInput(attrs={'class': 'form-control url-field first-tab-element'}),
        }


class UserBioForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('bio', )
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'style': 'height: 300px;'}),
        }

website/templates/management/breadcrumbs.html
<div class="content bg-gray-lighter">
    <div class="row items-push">
        <div class="col-sm-12">
            <div class="row items-push">
                <div class="col-sm-7">
                    <h1 class="page-heading">
                        {{ title }}
                    </h1>
                </div>
                <div class="col-sm-5 text-right hidden-xs">
                    <ol class="breadcrumb push-10-t">
                        <li>Home</li>
                        {% for breadcrumb in breadcrumbs %}
                            <li>
                                {% if breadcrumb.url %}
                                    <a class="link-effect" href="{{ breadcrumb.url }}">{{ breadcrumb.name }}</a>
                                {% else %}
                                    {{ breadcrumb.name }}
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

website/templates/management/manager_form.html
{% load extras %}


{% for field in form %}
    <div class="form-group row {% if field.errors %}has-error{% endif %}">
        {% if field.field.widget|get_class_name != "HiddenInput" %}
        <label for="{{ field.id_for_label }}"
               class="control-label col-md-{{ label_size }}">{{ field.label }}</label>
        {% endif %}
        <div class="col-md-{{ field_size }}">
            {% if field.field.widget|get_class_name == "CheckboxInput" %}
                <label for="{{ field.id_for_label }}"
                       class="css-input switch switch-sm switch-primary">
                    {{ field }}<span></span>
                </label>
            {% else %}
                {{ field }}
                {{ field.help_text }}
                {% if field.errors %}
                    <span class="help-block">
                        {{ field.help_text }}
                        {% for error in field.errors %}{{ error }}{% endfor %}
                    </span>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endfor %}

website/templates/management/manager_mail_template_form.html
{% extends "management/manager_base.html" %}

{% block content %}
    <main id="main-container">
    {% include 'management/breadcrumbs.html' %}
        <div class="block">
            <div class="block-content row">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {% for field in form %}
                        <div class="form-group row {% if field.errors %}has-error{% endif %}">
                            <label for="{{ field.id_for_label }}" class="control-label col-lg-1 col-md-1">{{ field.label }}</label>
                            <div class="col-lg-5 col-md-5">
                                {{ field }}
                                {{ field.help_text }}
                                {% if field.errors %}
                                    <span class="help-block">
                                        {{ field.help_text }}
                                        {% for error in field.errors %}{{ error }}{% endfor %}
                                    </span>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                    <input class="btn btn-info btn-lg" type="submit" value="{{ submit }}"/>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

website/templates/management/manager_mail_templates.html
{% extends "management/manager_base.html" %}
{% load management_extras %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" id="css-custom"
          href="{% static 'js/plugins/datatables/jquery.dataTables.min.css' %}">
{% endblock %}

{% block content %}
    <main id="main-container">
        {% include 'management/breadcrumbs.html' with title='Email Templates' %}
        <div class="block">
            <div class="block-header">
                <a href="{% url 'management:mail-template-add' property.id %}" class="btn btn-info btn-lg"
                   style="float: right;">
                    Add New Email Template
                </a>
            </div>
            <div class="block-content">
                <div id="email-table-block" class="block block-rounded">
                    <div class="block-header">
                        <ul class="block-options">
                            <li>
                                <button type="button" data-toggle="block-option"
                                        onclick="$('email-table').DataTable().page('previous').draw('page');"><i
                                        class="si si-arrow-left"></i></button>
                            </li>
                            <li>
                                <button type="button" data-toggle="block-option"
                                        onclick="$('#email-table').DataTable().page('next').draw('page');"><i
                                        class="si si-arrow-right"></i></button>
                            </li>
                            <li>
                                <button type="button" data-toggle="block-option"
                                        onclick="$('#email-table').DataTable().draw('page');"><i
                                        class="si si-refresh"></i></button>
                            </li>
                            <li>
                                <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i
                                        class="si si-size-fullscreen"></i></button>
                            </li>
                        </ul>
                    </div>
                    <div class="block-content">
                        <div class="dataTables_wrapper form-inline dt-bootstrap no-footer"
                             id="email-table_wrapper">
                            <div class="row">
                                <div class="col-sm-12">
                                    <table aria-describedby="email-table_info" role="grid" id="email-table"
                                           class="table table-bordered table-striped full-width-table js-dataTable-full dataTable no-footer table-hover">
                                        <thead>
                                        <tr role="row">
                                            <th aria-label="Name: activate to sort column ascending"
                                                colspan="1" rowspan="1" aria-controls="invitation-table" tabindex="0"
                                                class="sorting">Email Templates
                                            </th>
                                            <th aria-label="Access: activate to sort column ascending" colspan="1"
                                                rowspan="1"
                                                aria-controls="email-table" tabindex="0" class="hidden-xs"
                                            >Delete?
                                            </th>
                                        </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script src="{% static 'js/plugins/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'js/custom-scripts/dataTables.styles.js' %}"></script>
    <script src="{% static 'js/custom-scripts/email-table.js' %}?v=0002"></script>
    <script>
        changeStyles();
        initEmailTable('{% url 'management:mail-template-list' property.id %}', {{ property.id }});
    </script>
{% endblock %}

website/templates/management/manager_org_questions.html
{% extends "management/manager_base.html" %}
{% load management_extras %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" id="css-custom"
          href="{% static 'js/plugins/datatables/jquery.dataTables.min.css' %}">
{% endblock %}

{% block content %}
    <main id="main-container">
        {% include 'management/breadcrumbs.html' with title="Tenant Profile Questions" %}
        <div class="block">
            <div class="block-header">
                <a href="{% url 'management:org-question-add' property.id %}" class="btn btn-info btn-lg"
                   style="float: right;">
                    Add a Tenant Profile Question
                </a>
            </div>
            <div class="block-content">
                <div id="org-questions-table-block" class="block block-rounded">
                    <div class="block-header">
                        <ul class="block-options">
                            <li>
                                <button aria-expanded="false" type="button"
                                        onclick="location.href=window.location.href+'?format=csv'"><i
                                        class="si si-cloud-download"></i></button>
                            </li>
                            <li>
                                <button type="button" data-toggle="block-option"
                                        onclick="$('#org-questions-table').DataTable().page('previous').draw('page');">
                                    <i class="si si-arrow-left"></i></button>
                            </li>
                            <li>
                                <button type="button" data-toggle="block-option"
                                        onclick="$('#org-questions-table').DataTable().page('next').draw('page');"><i
                                        class="si si-arrow-right"></i></button>
                            </li>
                            <li>
                                <button type="button" data-toggle="block-option"
                                        onclick="$('#org-questions-table').DataTable().draw('page');"><i
                                        class="si si-refresh"></i></button>
                            </li>
                            <li>
                                <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i
                                        class="si si-size-fullscreen"></i></button>
                            </li>
                        </ul>
                    </div>
                    <div class="block-content">
                        <div class="dataTables_wrapper form-inline dt-bootstrap no-footer"
                             id="DataTables_Table_1_wrapper">
                            <div class="row">
                                <div class="col-sm-12">
                                    <table aria-describedby="org-questions-table_info" role="grid"
                                           id="org-questions-table"
                                           class="table table-bordered table-striped js-dataTable-full dataTable no-footer table-hover">
                                        <thead>
                                        <tr role="row">
                                            <th aria-label="Name: activate to sort column ascending"
                                                colspan="1" rowspan="1" aria-controls="org-questions-table" tabindex="0"
                                                class="sorting">Question
                                            </th>
                                            <th aria-label="Email: activate to sort column ascending"
                                                colspan="1" rowspan="1" aria-controls="org-questions-table" tabindex="0"
                                                class="sorting">Required
                                            </th>
                                            <th aria-label="Name: activate to sort column ascending"
                                                colspan="1" rowspan="1" aria-controls="org-questions-table" tabindex="0"
                                                class="sorting">Sort Order
                                            </th>
                                            <th aria-label="Name: activate to sort column ascending"
                                                colspan="1" rowspan="1" aria-controls="org-questions-table" tabindex="0"
                                                class="sorting">Status
                                            </th>
                                            <th aria-label="Name: activate to sort column ascending"
                                                colspan="1" rowspan="1" aria-controls="org-questions-table" tabindex="0"
                                                class="sorting">Created At
                                            </th>
                                            <th aria-label="Name: activate to sort column ascending"
                                                colspan="1" rowspan="1" aria-controls="org-questions-table" tabindex="0"
                                                class="sorting">Updated At
                                            </th>
                                        </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script src="{% static 'js/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/custom-scripts/dataTables.styles.js' %}"></script>
    <script src="{% static 'js/custom-scripts/org-questions-table.js' %}?v=0003"></script>
    <script>
        changeStyles();
        initOrgQuestionsTable('{% url 'management:org-questions-list' property.id %}', '/management/org_question/{{ property.id }}/');
    </script>
{% endblock %}